/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteRouteImport } from './routes/_authed/profile/route'
import { Route as AuthedGroupsRouteRouteImport } from './routes/_authed/groups/route'
import { Route as AuthedFeedbacksRouteRouteImport } from './routes/_authed/feedbacks/route'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedFeedbacksIndexRouteImport } from './routes/_authed/feedbacks/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedGroupsMyRouteImport } from './routes/_authed/groups/my'
import { Route as AuthedGroupsCreateRouteImport } from './routes/_authed/groups/create'
import { Route as AuthedGroupsAllRouteImport } from './routes/_authed/groups/all'
import { Route as AuthedFeedbacksCreateRouteImport } from './routes/_authed/feedbacks/create'
import { Route as AuthedAdminStatsRouteImport } from './routes/_authed/admin/stats'
import { Route as AuthedGroupsSlugRouteRouteImport } from './routes/_authed/groups/$slug/route'
import { Route as AuthedFeedbacksFeedbackIdRouteRouteImport } from './routes/_authed/feedbacks/$feedbackId/route'
import { Route as AuthedAdminGroupsRouteRouteImport } from './routes/_authed/admin/groups/route'
import { Route as AuthedAdminFeedbacksRouteRouteImport } from './routes/_authed/admin/feedbacks/route'
import { Route as AuthedGroupsSlugIndexRouteImport } from './routes/_authed/groups/$slug/index'
import { Route as AuthedFeedbacksFeedbackIdIndexRouteImport } from './routes/_authed/feedbacks/$feedbackId/index'
import { Route as AuthedAdminGroupsIndexRouteImport } from './routes/_authed/admin/groups/index'
import { Route as AuthedAdminFeedbacksIndexRouteImport } from './routes/_authed/admin/feedbacks/index'
import { Route as AuthedGroupsSlugSettingsRouteImport } from './routes/_authed/groups/$slug/settings'
import { Route as AuthedGroupsSlugMembersRouteImport } from './routes/_authed/groups/$slug/members'
import { Route as AuthedGroupsSlugAdminRouteImport } from './routes/_authed/groups/$slug/admin'
import { Route as AuthedFeedbacksFeedbackIdLogsRouteImport } from './routes/_authed/feedbacks/$feedbackId/logs'
import { Route as AuthedAdminGroupsPendingRouteImport } from './routes/_authed/admin/groups/pending'
import { Route as AuthedAdminFeedbacksPendingRouteImport } from './routes/_authed/admin/feedbacks/pending'
import { Route as AuthedGroupsSlugPostsRouteRouteImport } from './routes/_authed/groups/$slug/posts/route'
import { Route as AuthedGroupsSlugPostsIndexRouteImport } from './routes/_authed/groups/$slug/posts/index'
import { Route as AuthedGroupsSlugPostsCreateRouteImport } from './routes/_authed/groups/$slug/posts/create'
import { Route as AuthedGroupsSlugPostsAnnouncementsRouteImport } from './routes/_authed/groups/$slug/posts/announcements'
import { Route as AuthedGroupsSlugPostsPostIdRouteRouteImport } from './routes/_authed/groups/$slug/posts/$postId/route'
import { Route as AuthedGroupsSlugPostsPostIdIndexRouteImport } from './routes/_authed/groups/$slug/posts/$postId/index'
import { Route as AuthedGroupsSlugPostsPostIdEditRouteImport } from './routes/_authed/groups/$slug/posts/$postId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRouteRoute = AuthedProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedGroupsRouteRoute = AuthedGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFeedbacksRouteRoute = AuthedFeedbacksRouteRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProfileRouteRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedFeedbacksIndexRoute = AuthedFeedbacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedFeedbacksRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedGroupsMyRoute = AuthedGroupsMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedGroupsCreateRoute = AuthedGroupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedGroupsAllRoute = AuthedGroupsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedFeedbacksCreateRoute = AuthedFeedbacksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedFeedbacksRouteRoute,
} as any)
const AuthedAdminStatsRoute = AuthedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedGroupsSlugRouteRoute = AuthedGroupsSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedFeedbacksFeedbackIdRouteRoute =
  AuthedFeedbacksFeedbackIdRouteRouteImport.update({
    id: '/$feedbackId',
    path: '/$feedbackId',
    getParentRoute: () => AuthedFeedbacksRouteRoute,
  } as any)
const AuthedAdminGroupsRouteRoute = AuthedAdminGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminFeedbacksRouteRoute =
  AuthedAdminFeedbacksRouteRouteImport.update({
    id: '/feedbacks',
    path: '/feedbacks',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedGroupsSlugIndexRoute = AuthedGroupsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGroupsSlugRouteRoute,
} as any)
const AuthedFeedbacksFeedbackIdIndexRoute =
  AuthedFeedbacksFeedbackIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFeedbacksFeedbackIdRouteRoute,
  } as any)
const AuthedAdminGroupsIndexRoute = AuthedAdminGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminGroupsRouteRoute,
} as any)
const AuthedAdminFeedbacksIndexRoute =
  AuthedAdminFeedbacksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAdminFeedbacksRouteRoute,
  } as any)
const AuthedGroupsSlugSettingsRoute =
  AuthedGroupsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedGroupsSlugRouteRoute,
  } as any)
const AuthedGroupsSlugMembersRoute = AuthedGroupsSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedGroupsSlugRouteRoute,
} as any)
const AuthedGroupsSlugAdminRoute = AuthedGroupsSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedGroupsSlugRouteRoute,
} as any)
const AuthedFeedbacksFeedbackIdLogsRoute =
  AuthedFeedbacksFeedbackIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthedFeedbacksFeedbackIdRouteRoute,
  } as any)
const AuthedAdminGroupsPendingRoute =
  AuthedAdminGroupsPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthedAdminGroupsRouteRoute,
  } as any)
const AuthedAdminFeedbacksPendingRoute =
  AuthedAdminFeedbacksPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthedAdminFeedbacksRouteRoute,
  } as any)
const AuthedGroupsSlugPostsRouteRoute =
  AuthedGroupsSlugPostsRouteRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthedGroupsSlugRouteRoute,
  } as any)
const AuthedGroupsSlugPostsIndexRoute =
  AuthedGroupsSlugPostsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedGroupsSlugPostsRouteRoute,
  } as any)
const AuthedGroupsSlugPostsCreateRoute =
  AuthedGroupsSlugPostsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthedGroupsSlugPostsRouteRoute,
  } as any)
const AuthedGroupsSlugPostsAnnouncementsRoute =
  AuthedGroupsSlugPostsAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthedGroupsSlugPostsRouteRoute,
  } as any)
const AuthedGroupsSlugPostsPostIdRouteRoute =
  AuthedGroupsSlugPostsPostIdRouteRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => AuthedGroupsSlugPostsRouteRoute,
  } as any)
const AuthedGroupsSlugPostsPostIdIndexRoute =
  AuthedGroupsSlugPostsPostIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedGroupsSlugPostsPostIdRouteRoute,
  } as any)
const AuthedGroupsSlugPostsPostIdEditRoute =
  AuthedGroupsSlugPostsPostIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedGroupsSlugPostsPostIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/feedbacks': typeof AuthedFeedbacksRouteRouteWithChildren
  '/groups': typeof AuthedGroupsRouteRouteWithChildren
  '/profile': typeof AuthedProfileRouteRouteWithChildren
  '/admin/feedbacks': typeof AuthedAdminFeedbacksRouteRouteWithChildren
  '/admin/groups': typeof AuthedAdminGroupsRouteRouteWithChildren
  '/feedbacks/$feedbackId': typeof AuthedFeedbacksFeedbackIdRouteRouteWithChildren
  '/groups/$slug': typeof AuthedGroupsSlugRouteRouteWithChildren
  '/admin/stats': typeof AuthedAdminStatsRoute
  '/feedbacks/create': typeof AuthedFeedbacksCreateRoute
  '/groups/all': typeof AuthedGroupsAllRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/groups/my': typeof AuthedGroupsMyRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/feedbacks/': typeof AuthedFeedbacksIndexRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/groups/$slug/posts': typeof AuthedGroupsSlugPostsRouteRouteWithChildren
  '/admin/feedbacks/pending': typeof AuthedAdminFeedbacksPendingRoute
  '/admin/groups/pending': typeof AuthedAdminGroupsPendingRoute
  '/feedbacks/$feedbackId/logs': typeof AuthedFeedbacksFeedbackIdLogsRoute
  '/groups/$slug/admin': typeof AuthedGroupsSlugAdminRoute
  '/groups/$slug/members': typeof AuthedGroupsSlugMembersRoute
  '/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/admin/feedbacks/': typeof AuthedAdminFeedbacksIndexRoute
  '/admin/groups/': typeof AuthedAdminGroupsIndexRoute
  '/feedbacks/$feedbackId/': typeof AuthedFeedbacksFeedbackIdIndexRoute
  '/groups/$slug/': typeof AuthedGroupsSlugIndexRoute
  '/groups/$slug/posts/$postId': typeof AuthedGroupsSlugPostsPostIdRouteRouteWithChildren
  '/groups/$slug/posts/announcements': typeof AuthedGroupsSlugPostsAnnouncementsRoute
  '/groups/$slug/posts/create': typeof AuthedGroupsSlugPostsCreateRoute
  '/groups/$slug/posts/': typeof AuthedGroupsSlugPostsIndexRoute
  '/groups/$slug/posts/$postId/edit': typeof AuthedGroupsSlugPostsPostIdEditRoute
  '/groups/$slug/posts/$postId/': typeof AuthedGroupsSlugPostsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin/stats': typeof AuthedAdminStatsRoute
  '/feedbacks/create': typeof AuthedFeedbacksCreateRoute
  '/groups/all': typeof AuthedGroupsAllRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/groups/my': typeof AuthedGroupsMyRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/feedbacks': typeof AuthedFeedbacksIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/admin/feedbacks/pending': typeof AuthedAdminFeedbacksPendingRoute
  '/admin/groups/pending': typeof AuthedAdminGroupsPendingRoute
  '/feedbacks/$feedbackId/logs': typeof AuthedFeedbacksFeedbackIdLogsRoute
  '/groups/$slug/admin': typeof AuthedGroupsSlugAdminRoute
  '/groups/$slug/members': typeof AuthedGroupsSlugMembersRoute
  '/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/admin/feedbacks': typeof AuthedAdminFeedbacksIndexRoute
  '/admin/groups': typeof AuthedAdminGroupsIndexRoute
  '/feedbacks/$feedbackId': typeof AuthedFeedbacksFeedbackIdIndexRoute
  '/groups/$slug': typeof AuthedGroupsSlugIndexRoute
  '/groups/$slug/posts/announcements': typeof AuthedGroupsSlugPostsAnnouncementsRoute
  '/groups/$slug/posts/create': typeof AuthedGroupsSlugPostsCreateRoute
  '/groups/$slug/posts': typeof AuthedGroupsSlugPostsIndexRoute
  '/groups/$slug/posts/$postId/edit': typeof AuthedGroupsSlugPostsPostIdEditRoute
  '/groups/$slug/posts/$postId': typeof AuthedGroupsSlugPostsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/feedbacks': typeof AuthedFeedbacksRouteRouteWithChildren
  '/_authed/groups': typeof AuthedGroupsRouteRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRouteRouteWithChildren
  '/_authed/admin/feedbacks': typeof AuthedAdminFeedbacksRouteRouteWithChildren
  '/_authed/admin/groups': typeof AuthedAdminGroupsRouteRouteWithChildren
  '/_authed/feedbacks/$feedbackId': typeof AuthedFeedbacksFeedbackIdRouteRouteWithChildren
  '/_authed/groups/$slug': typeof AuthedGroupsSlugRouteRouteWithChildren
  '/_authed/admin/stats': typeof AuthedAdminStatsRoute
  '/_authed/feedbacks/create': typeof AuthedFeedbacksCreateRoute
  '/_authed/groups/all': typeof AuthedGroupsAllRoute
  '/_authed/groups/create': typeof AuthedGroupsCreateRoute
  '/_authed/groups/my': typeof AuthedGroupsMyRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/feedbacks/': typeof AuthedFeedbacksIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/groups/$slug/posts': typeof AuthedGroupsSlugPostsRouteRouteWithChildren
  '/_authed/admin/feedbacks/pending': typeof AuthedAdminFeedbacksPendingRoute
  '/_authed/admin/groups/pending': typeof AuthedAdminGroupsPendingRoute
  '/_authed/feedbacks/$feedbackId/logs': typeof AuthedFeedbacksFeedbackIdLogsRoute
  '/_authed/groups/$slug/admin': typeof AuthedGroupsSlugAdminRoute
  '/_authed/groups/$slug/members': typeof AuthedGroupsSlugMembersRoute
  '/_authed/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/_authed/admin/feedbacks/': typeof AuthedAdminFeedbacksIndexRoute
  '/_authed/admin/groups/': typeof AuthedAdminGroupsIndexRoute
  '/_authed/feedbacks/$feedbackId/': typeof AuthedFeedbacksFeedbackIdIndexRoute
  '/_authed/groups/$slug/': typeof AuthedGroupsSlugIndexRoute
  '/_authed/groups/$slug/posts/$postId': typeof AuthedGroupsSlugPostsPostIdRouteRouteWithChildren
  '/_authed/groups/$slug/posts/announcements': typeof AuthedGroupsSlugPostsAnnouncementsRoute
  '/_authed/groups/$slug/posts/create': typeof AuthedGroupsSlugPostsCreateRoute
  '/_authed/groups/$slug/posts/': typeof AuthedGroupsSlugPostsIndexRoute
  '/_authed/groups/$slug/posts/$postId/edit': typeof AuthedGroupsSlugPostsPostIdEditRoute
  '/_authed/groups/$slug/posts/$postId/': typeof AuthedGroupsSlugPostsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin'
    | '/feedbacks'
    | '/groups'
    | '/profile'
    | '/admin/feedbacks'
    | '/admin/groups'
    | '/feedbacks/$feedbackId'
    | '/groups/$slug'
    | '/admin/stats'
    | '/feedbacks/create'
    | '/groups/all'
    | '/groups/create'
    | '/groups/my'
    | '/admin/'
    | '/feedbacks/'
    | '/groups/'
    | '/profile/'
    | '/groups/$slug/posts'
    | '/admin/feedbacks/pending'
    | '/admin/groups/pending'
    | '/feedbacks/$feedbackId/logs'
    | '/groups/$slug/admin'
    | '/groups/$slug/members'
    | '/groups/$slug/settings'
    | '/admin/feedbacks/'
    | '/admin/groups/'
    | '/feedbacks/$feedbackId/'
    | '/groups/$slug/'
    | '/groups/$slug/posts/$postId'
    | '/groups/$slug/posts/announcements'
    | '/groups/$slug/posts/create'
    | '/groups/$slug/posts/'
    | '/groups/$slug/posts/$postId/edit'
    | '/groups/$slug/posts/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin/stats'
    | '/feedbacks/create'
    | '/groups/all'
    | '/groups/create'
    | '/groups/my'
    | '/admin'
    | '/feedbacks'
    | '/groups'
    | '/profile'
    | '/admin/feedbacks/pending'
    | '/admin/groups/pending'
    | '/feedbacks/$feedbackId/logs'
    | '/groups/$slug/admin'
    | '/groups/$slug/members'
    | '/groups/$slug/settings'
    | '/admin/feedbacks'
    | '/admin/groups'
    | '/feedbacks/$feedbackId'
    | '/groups/$slug'
    | '/groups/$slug/posts/announcements'
    | '/groups/$slug/posts/create'
    | '/groups/$slug/posts'
    | '/groups/$slug/posts/$postId/edit'
    | '/groups/$slug/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/feedbacks'
    | '/_authed/groups'
    | '/_authed/profile'
    | '/_authed/admin/feedbacks'
    | '/_authed/admin/groups'
    | '/_authed/feedbacks/$feedbackId'
    | '/_authed/groups/$slug'
    | '/_authed/admin/stats'
    | '/_authed/feedbacks/create'
    | '/_authed/groups/all'
    | '/_authed/groups/create'
    | '/_authed/groups/my'
    | '/_authed/admin/'
    | '/_authed/feedbacks/'
    | '/_authed/groups/'
    | '/_authed/profile/'
    | '/_authed/groups/$slug/posts'
    | '/_authed/admin/feedbacks/pending'
    | '/_authed/admin/groups/pending'
    | '/_authed/feedbacks/$feedbackId/logs'
    | '/_authed/groups/$slug/admin'
    | '/_authed/groups/$slug/members'
    | '/_authed/groups/$slug/settings'
    | '/_authed/admin/feedbacks/'
    | '/_authed/admin/groups/'
    | '/_authed/feedbacks/$feedbackId/'
    | '/_authed/groups/$slug/'
    | '/_authed/groups/$slug/posts/$postId'
    | '/_authed/groups/$slug/posts/announcements'
    | '/_authed/groups/$slug/posts/create'
    | '/_authed/groups/$slug/posts/'
    | '/_authed/groups/$slug/posts/$postId/edit'
    | '/_authed/groups/$slug/posts/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/groups': {
      id: '/_authed/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthedGroupsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/feedbacks': {
      id: '/_authed/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AuthedFeedbacksRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedProfileRouteRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/feedbacks/': {
      id: '/_authed/feedbacks/'
      path: '/'
      fullPath: '/feedbacks/'
      preLoaderRoute: typeof AuthedFeedbacksIndexRouteImport
      parentRoute: typeof AuthedFeedbacksRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/groups/my': {
      id: '/_authed/groups/my'
      path: '/my'
      fullPath: '/groups/my'
      preLoaderRoute: typeof AuthedGroupsMyRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/groups/create': {
      id: '/_authed/groups/create'
      path: '/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AuthedGroupsCreateRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/groups/all': {
      id: '/_authed/groups/all'
      path: '/all'
      fullPath: '/groups/all'
      preLoaderRoute: typeof AuthedGroupsAllRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/feedbacks/create': {
      id: '/_authed/feedbacks/create'
      path: '/create'
      fullPath: '/feedbacks/create'
      preLoaderRoute: typeof AuthedFeedbacksCreateRouteImport
      parentRoute: typeof AuthedFeedbacksRouteRoute
    }
    '/_authed/admin/stats': {
      id: '/_authed/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthedAdminStatsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/groups/$slug': {
      id: '/_authed/groups/$slug'
      path: '/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof AuthedGroupsSlugRouteRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/feedbacks/$feedbackId': {
      id: '/_authed/feedbacks/$feedbackId'
      path: '/$feedbackId'
      fullPath: '/feedbacks/$feedbackId'
      preLoaderRoute: typeof AuthedFeedbacksFeedbackIdRouteRouteImport
      parentRoute: typeof AuthedFeedbacksRouteRoute
    }
    '/_authed/admin/groups': {
      id: '/_authed/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthedAdminGroupsRouteRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/feedbacks': {
      id: '/_authed/admin/feedbacks'
      path: '/feedbacks'
      fullPath: '/admin/feedbacks'
      preLoaderRoute: typeof AuthedAdminFeedbacksRouteRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/groups/$slug/': {
      id: '/_authed/groups/$slug/'
      path: '/'
      fullPath: '/groups/$slug/'
      preLoaderRoute: typeof AuthedGroupsSlugIndexRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/feedbacks/$feedbackId/': {
      id: '/_authed/feedbacks/$feedbackId/'
      path: '/'
      fullPath: '/feedbacks/$feedbackId/'
      preLoaderRoute: typeof AuthedFeedbacksFeedbackIdIndexRouteImport
      parentRoute: typeof AuthedFeedbacksFeedbackIdRouteRoute
    }
    '/_authed/admin/groups/': {
      id: '/_authed/admin/groups/'
      path: '/'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AuthedAdminGroupsIndexRouteImport
      parentRoute: typeof AuthedAdminGroupsRouteRoute
    }
    '/_authed/admin/feedbacks/': {
      id: '/_authed/admin/feedbacks/'
      path: '/'
      fullPath: '/admin/feedbacks/'
      preLoaderRoute: typeof AuthedAdminFeedbacksIndexRouteImport
      parentRoute: typeof AuthedAdminFeedbacksRouteRoute
    }
    '/_authed/groups/$slug/settings': {
      id: '/_authed/groups/$slug/settings'
      path: '/settings'
      fullPath: '/groups/$slug/settings'
      preLoaderRoute: typeof AuthedGroupsSlugSettingsRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/groups/$slug/members': {
      id: '/_authed/groups/$slug/members'
      path: '/members'
      fullPath: '/groups/$slug/members'
      preLoaderRoute: typeof AuthedGroupsSlugMembersRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/groups/$slug/admin': {
      id: '/_authed/groups/$slug/admin'
      path: '/admin'
      fullPath: '/groups/$slug/admin'
      preLoaderRoute: typeof AuthedGroupsSlugAdminRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/feedbacks/$feedbackId/logs': {
      id: '/_authed/feedbacks/$feedbackId/logs'
      path: '/logs'
      fullPath: '/feedbacks/$feedbackId/logs'
      preLoaderRoute: typeof AuthedFeedbacksFeedbackIdLogsRouteImport
      parentRoute: typeof AuthedFeedbacksFeedbackIdRouteRoute
    }
    '/_authed/admin/groups/pending': {
      id: '/_authed/admin/groups/pending'
      path: '/pending'
      fullPath: '/admin/groups/pending'
      preLoaderRoute: typeof AuthedAdminGroupsPendingRouteImport
      parentRoute: typeof AuthedAdminGroupsRouteRoute
    }
    '/_authed/admin/feedbacks/pending': {
      id: '/_authed/admin/feedbacks/pending'
      path: '/pending'
      fullPath: '/admin/feedbacks/pending'
      preLoaderRoute: typeof AuthedAdminFeedbacksPendingRouteImport
      parentRoute: typeof AuthedAdminFeedbacksRouteRoute
    }
    '/_authed/groups/$slug/posts': {
      id: '/_authed/groups/$slug/posts'
      path: '/posts'
      fullPath: '/groups/$slug/posts'
      preLoaderRoute: typeof AuthedGroupsSlugPostsRouteRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/groups/$slug/posts/': {
      id: '/_authed/groups/$slug/posts/'
      path: '/'
      fullPath: '/groups/$slug/posts/'
      preLoaderRoute: typeof AuthedGroupsSlugPostsIndexRouteImport
      parentRoute: typeof AuthedGroupsSlugPostsRouteRoute
    }
    '/_authed/groups/$slug/posts/create': {
      id: '/_authed/groups/$slug/posts/create'
      path: '/create'
      fullPath: '/groups/$slug/posts/create'
      preLoaderRoute: typeof AuthedGroupsSlugPostsCreateRouteImport
      parentRoute: typeof AuthedGroupsSlugPostsRouteRoute
    }
    '/_authed/groups/$slug/posts/announcements': {
      id: '/_authed/groups/$slug/posts/announcements'
      path: '/announcements'
      fullPath: '/groups/$slug/posts/announcements'
      preLoaderRoute: typeof AuthedGroupsSlugPostsAnnouncementsRouteImport
      parentRoute: typeof AuthedGroupsSlugPostsRouteRoute
    }
    '/_authed/groups/$slug/posts/$postId': {
      id: '/_authed/groups/$slug/posts/$postId'
      path: '/$postId'
      fullPath: '/groups/$slug/posts/$postId'
      preLoaderRoute: typeof AuthedGroupsSlugPostsPostIdRouteRouteImport
      parentRoute: typeof AuthedGroupsSlugPostsRouteRoute
    }
    '/_authed/groups/$slug/posts/$postId/': {
      id: '/_authed/groups/$slug/posts/$postId/'
      path: '/'
      fullPath: '/groups/$slug/posts/$postId/'
      preLoaderRoute: typeof AuthedGroupsSlugPostsPostIdIndexRouteImport
      parentRoute: typeof AuthedGroupsSlugPostsPostIdRouteRoute
    }
    '/_authed/groups/$slug/posts/$postId/edit': {
      id: '/_authed/groups/$slug/posts/$postId/edit'
      path: '/edit'
      fullPath: '/groups/$slug/posts/$postId/edit'
      preLoaderRoute: typeof AuthedGroupsSlugPostsPostIdEditRouteImport
      parentRoute: typeof AuthedGroupsSlugPostsPostIdRouteRoute
    }
  }
}

interface AuthedAdminFeedbacksRouteRouteChildren {
  AuthedAdminFeedbacksPendingRoute: typeof AuthedAdminFeedbacksPendingRoute
  AuthedAdminFeedbacksIndexRoute: typeof AuthedAdminFeedbacksIndexRoute
}

const AuthedAdminFeedbacksRouteRouteChildren: AuthedAdminFeedbacksRouteRouteChildren =
  {
    AuthedAdminFeedbacksPendingRoute: AuthedAdminFeedbacksPendingRoute,
    AuthedAdminFeedbacksIndexRoute: AuthedAdminFeedbacksIndexRoute,
  }

const AuthedAdminFeedbacksRouteRouteWithChildren =
  AuthedAdminFeedbacksRouteRoute._addFileChildren(
    AuthedAdminFeedbacksRouteRouteChildren,
  )

interface AuthedAdminGroupsRouteRouteChildren {
  AuthedAdminGroupsPendingRoute: typeof AuthedAdminGroupsPendingRoute
  AuthedAdminGroupsIndexRoute: typeof AuthedAdminGroupsIndexRoute
}

const AuthedAdminGroupsRouteRouteChildren: AuthedAdminGroupsRouteRouteChildren =
  {
    AuthedAdminGroupsPendingRoute: AuthedAdminGroupsPendingRoute,
    AuthedAdminGroupsIndexRoute: AuthedAdminGroupsIndexRoute,
  }

const AuthedAdminGroupsRouteRouteWithChildren =
  AuthedAdminGroupsRouteRoute._addFileChildren(
    AuthedAdminGroupsRouteRouteChildren,
  )

interface AuthedAdminRouteRouteChildren {
  AuthedAdminFeedbacksRouteRoute: typeof AuthedAdminFeedbacksRouteRouteWithChildren
  AuthedAdminGroupsRouteRoute: typeof AuthedAdminGroupsRouteRouteWithChildren
  AuthedAdminStatsRoute: typeof AuthedAdminStatsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminFeedbacksRouteRoute: AuthedAdminFeedbacksRouteRouteWithChildren,
  AuthedAdminGroupsRouteRoute: AuthedAdminGroupsRouteRouteWithChildren,
  AuthedAdminStatsRoute: AuthedAdminStatsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedFeedbacksFeedbackIdRouteRouteChildren {
  AuthedFeedbacksFeedbackIdLogsRoute: typeof AuthedFeedbacksFeedbackIdLogsRoute
  AuthedFeedbacksFeedbackIdIndexRoute: typeof AuthedFeedbacksFeedbackIdIndexRoute
}

const AuthedFeedbacksFeedbackIdRouteRouteChildren: AuthedFeedbacksFeedbackIdRouteRouteChildren =
  {
    AuthedFeedbacksFeedbackIdLogsRoute: AuthedFeedbacksFeedbackIdLogsRoute,
    AuthedFeedbacksFeedbackIdIndexRoute: AuthedFeedbacksFeedbackIdIndexRoute,
  }

const AuthedFeedbacksFeedbackIdRouteRouteWithChildren =
  AuthedFeedbacksFeedbackIdRouteRoute._addFileChildren(
    AuthedFeedbacksFeedbackIdRouteRouteChildren,
  )

interface AuthedFeedbacksRouteRouteChildren {
  AuthedFeedbacksFeedbackIdRouteRoute: typeof AuthedFeedbacksFeedbackIdRouteRouteWithChildren
  AuthedFeedbacksCreateRoute: typeof AuthedFeedbacksCreateRoute
  AuthedFeedbacksIndexRoute: typeof AuthedFeedbacksIndexRoute
}

const AuthedFeedbacksRouteRouteChildren: AuthedFeedbacksRouteRouteChildren = {
  AuthedFeedbacksFeedbackIdRouteRoute:
    AuthedFeedbacksFeedbackIdRouteRouteWithChildren,
  AuthedFeedbacksCreateRoute: AuthedFeedbacksCreateRoute,
  AuthedFeedbacksIndexRoute: AuthedFeedbacksIndexRoute,
}

const AuthedFeedbacksRouteRouteWithChildren =
  AuthedFeedbacksRouteRoute._addFileChildren(AuthedFeedbacksRouteRouteChildren)

interface AuthedGroupsSlugPostsPostIdRouteRouteChildren {
  AuthedGroupsSlugPostsPostIdEditRoute: typeof AuthedGroupsSlugPostsPostIdEditRoute
  AuthedGroupsSlugPostsPostIdIndexRoute: typeof AuthedGroupsSlugPostsPostIdIndexRoute
}

const AuthedGroupsSlugPostsPostIdRouteRouteChildren: AuthedGroupsSlugPostsPostIdRouteRouteChildren =
  {
    AuthedGroupsSlugPostsPostIdEditRoute: AuthedGroupsSlugPostsPostIdEditRoute,
    AuthedGroupsSlugPostsPostIdIndexRoute:
      AuthedGroupsSlugPostsPostIdIndexRoute,
  }

const AuthedGroupsSlugPostsPostIdRouteRouteWithChildren =
  AuthedGroupsSlugPostsPostIdRouteRoute._addFileChildren(
    AuthedGroupsSlugPostsPostIdRouteRouteChildren,
  )

interface AuthedGroupsSlugPostsRouteRouteChildren {
  AuthedGroupsSlugPostsPostIdRouteRoute: typeof AuthedGroupsSlugPostsPostIdRouteRouteWithChildren
  AuthedGroupsSlugPostsAnnouncementsRoute: typeof AuthedGroupsSlugPostsAnnouncementsRoute
  AuthedGroupsSlugPostsCreateRoute: typeof AuthedGroupsSlugPostsCreateRoute
  AuthedGroupsSlugPostsIndexRoute: typeof AuthedGroupsSlugPostsIndexRoute
}

const AuthedGroupsSlugPostsRouteRouteChildren: AuthedGroupsSlugPostsRouteRouteChildren =
  {
    AuthedGroupsSlugPostsPostIdRouteRoute:
      AuthedGroupsSlugPostsPostIdRouteRouteWithChildren,
    AuthedGroupsSlugPostsAnnouncementsRoute:
      AuthedGroupsSlugPostsAnnouncementsRoute,
    AuthedGroupsSlugPostsCreateRoute: AuthedGroupsSlugPostsCreateRoute,
    AuthedGroupsSlugPostsIndexRoute: AuthedGroupsSlugPostsIndexRoute,
  }

const AuthedGroupsSlugPostsRouteRouteWithChildren =
  AuthedGroupsSlugPostsRouteRoute._addFileChildren(
    AuthedGroupsSlugPostsRouteRouteChildren,
  )

interface AuthedGroupsSlugRouteRouteChildren {
  AuthedGroupsSlugPostsRouteRoute: typeof AuthedGroupsSlugPostsRouteRouteWithChildren
  AuthedGroupsSlugAdminRoute: typeof AuthedGroupsSlugAdminRoute
  AuthedGroupsSlugMembersRoute: typeof AuthedGroupsSlugMembersRoute
  AuthedGroupsSlugSettingsRoute: typeof AuthedGroupsSlugSettingsRoute
  AuthedGroupsSlugIndexRoute: typeof AuthedGroupsSlugIndexRoute
}

const AuthedGroupsSlugRouteRouteChildren: AuthedGroupsSlugRouteRouteChildren = {
  AuthedGroupsSlugPostsRouteRoute: AuthedGroupsSlugPostsRouteRouteWithChildren,
  AuthedGroupsSlugAdminRoute: AuthedGroupsSlugAdminRoute,
  AuthedGroupsSlugMembersRoute: AuthedGroupsSlugMembersRoute,
  AuthedGroupsSlugSettingsRoute: AuthedGroupsSlugSettingsRoute,
  AuthedGroupsSlugIndexRoute: AuthedGroupsSlugIndexRoute,
}

const AuthedGroupsSlugRouteRouteWithChildren =
  AuthedGroupsSlugRouteRoute._addFileChildren(
    AuthedGroupsSlugRouteRouteChildren,
  )

interface AuthedGroupsRouteRouteChildren {
  AuthedGroupsSlugRouteRoute: typeof AuthedGroupsSlugRouteRouteWithChildren
  AuthedGroupsAllRoute: typeof AuthedGroupsAllRoute
  AuthedGroupsCreateRoute: typeof AuthedGroupsCreateRoute
  AuthedGroupsMyRoute: typeof AuthedGroupsMyRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
}

const AuthedGroupsRouteRouteChildren: AuthedGroupsRouteRouteChildren = {
  AuthedGroupsSlugRouteRoute: AuthedGroupsSlugRouteRouteWithChildren,
  AuthedGroupsAllRoute: AuthedGroupsAllRoute,
  AuthedGroupsCreateRoute: AuthedGroupsCreateRoute,
  AuthedGroupsMyRoute: AuthedGroupsMyRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
}

const AuthedGroupsRouteRouteWithChildren =
  AuthedGroupsRouteRoute._addFileChildren(AuthedGroupsRouteRouteChildren)

interface AuthedProfileRouteRouteChildren {
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedProfileRouteRouteChildren: AuthedProfileRouteRouteChildren = {
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedProfileRouteRouteWithChildren =
  AuthedProfileRouteRoute._addFileChildren(AuthedProfileRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedFeedbacksRouteRoute: typeof AuthedFeedbacksRouteRouteWithChildren
  AuthedGroupsRouteRoute: typeof AuthedGroupsRouteRouteWithChildren
  AuthedProfileRouteRoute: typeof AuthedProfileRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedFeedbacksRouteRoute: AuthedFeedbacksRouteRouteWithChildren,
  AuthedGroupsRouteRoute: AuthedGroupsRouteRouteWithChildren,
  AuthedProfileRouteRoute: AuthedProfileRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
