/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteRouteImport } from './routes/_authed/profile/route'
import { Route as AuthedPostsRouteRouteImport } from './routes/_authed/posts.route'
import { Route as AuthedGroupsRouteRouteImport } from './routes/_authed/groups/route'
import { Route as AuthedFeedbacksRouteRouteImport } from './routes/_authed/feedbacks/route'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedFeedbacksIndexRouteImport } from './routes/_authed/feedbacks/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'
import { Route as AuthedGroupsMyRouteImport } from './routes/_authed/groups/my'
import { Route as AuthedGroupsCreateRouteImport } from './routes/_authed/groups/create'
import { Route as AuthedGroupsAllRouteImport } from './routes/_authed/groups/all'
import { Route as AuthedGroupsSlugRouteImport } from './routes/_authed/groups/$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRouteRoute = AuthedProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsRouteRoute = AuthedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsRouteRoute = AuthedGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFeedbacksRouteRoute = AuthedFeedbacksRouteRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProfileRouteRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedFeedbacksIndexRoute = AuthedFeedbacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedFeedbacksRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRouteRoute,
} as any)
const AuthedGroupsMyRoute = AuthedGroupsMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedGroupsCreateRoute = AuthedGroupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedGroupsAllRoute = AuthedGroupsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedGroupsSlugRoute = AuthedGroupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/feedbacks': typeof AuthedFeedbacksRouteRouteWithChildren
  '/groups': typeof AuthedGroupsRouteRouteWithChildren
  '/posts': typeof AuthedPostsRouteRouteWithChildren
  '/profile': typeof AuthedProfileRouteRouteWithChildren
  '/groups/$slug': typeof AuthedGroupsSlugRoute
  '/groups/all': typeof AuthedGroupsAllRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/groups/my': typeof AuthedGroupsMyRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/feedbacks/': typeof AuthedFeedbacksIndexRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/groups/$slug': typeof AuthedGroupsSlugRoute
  '/groups/all': typeof AuthedGroupsAllRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/groups/my': typeof AuthedGroupsMyRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/feedbacks': typeof AuthedFeedbacksIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/feedbacks': typeof AuthedFeedbacksRouteRouteWithChildren
  '/_authed/groups': typeof AuthedGroupsRouteRouteWithChildren
  '/_authed/posts': typeof AuthedPostsRouteRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRouteRouteWithChildren
  '/_authed/groups/$slug': typeof AuthedGroupsSlugRoute
  '/_authed/groups/all': typeof AuthedGroupsAllRoute
  '/_authed/groups/create': typeof AuthedGroupsCreateRoute
  '/_authed/groups/my': typeof AuthedGroupsMyRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/feedbacks/': typeof AuthedFeedbacksIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin'
    | '/feedbacks'
    | '/groups'
    | '/posts'
    | '/profile'
    | '/groups/$slug'
    | '/groups/all'
    | '/groups/create'
    | '/groups/my'
    | '/posts/$postId'
    | '/admin/'
    | '/feedbacks/'
    | '/groups/'
    | '/posts/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/groups/$slug'
    | '/groups/all'
    | '/groups/create'
    | '/groups/my'
    | '/posts/$postId'
    | '/admin'
    | '/feedbacks'
    | '/groups'
    | '/posts'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/feedbacks'
    | '/_authed/groups'
    | '/_authed/posts'
    | '/_authed/profile'
    | '/_authed/groups/$slug'
    | '/_authed/groups/all'
    | '/_authed/groups/create'
    | '/_authed/groups/my'
    | '/_authed/posts/$postId'
    | '/_authed/admin/'
    | '/_authed/feedbacks/'
    | '/_authed/groups/'
    | '/_authed/posts/'
    | '/_authed/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups': {
      id: '/_authed/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthedGroupsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/feedbacks': {
      id: '/_authed/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AuthedFeedbacksRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedProfileRouteRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/feedbacks/': {
      id: '/_authed/feedbacks/'
      path: '/'
      fullPath: '/feedbacks/'
      preLoaderRoute: typeof AuthedFeedbacksIndexRouteImport
      parentRoute: typeof AuthedFeedbacksRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRouteRoute
    }
    '/_authed/groups/my': {
      id: '/_authed/groups/my'
      path: '/my'
      fullPath: '/groups/my'
      preLoaderRoute: typeof AuthedGroupsMyRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/groups/create': {
      id: '/_authed/groups/create'
      path: '/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AuthedGroupsCreateRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/groups/all': {
      id: '/_authed/groups/all'
      path: '/all'
      fullPath: '/groups/all'
      preLoaderRoute: typeof AuthedGroupsAllRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/groups/$slug': {
      id: '/_authed/groups/$slug'
      path: '/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof AuthedGroupsSlugRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedFeedbacksRouteRouteChildren {
  AuthedFeedbacksIndexRoute: typeof AuthedFeedbacksIndexRoute
}

const AuthedFeedbacksRouteRouteChildren: AuthedFeedbacksRouteRouteChildren = {
  AuthedFeedbacksIndexRoute: AuthedFeedbacksIndexRoute,
}

const AuthedFeedbacksRouteRouteWithChildren =
  AuthedFeedbacksRouteRoute._addFileChildren(AuthedFeedbacksRouteRouteChildren)

interface AuthedGroupsRouteRouteChildren {
  AuthedGroupsSlugRoute: typeof AuthedGroupsSlugRoute
  AuthedGroupsAllRoute: typeof AuthedGroupsAllRoute
  AuthedGroupsCreateRoute: typeof AuthedGroupsCreateRoute
  AuthedGroupsMyRoute: typeof AuthedGroupsMyRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
}

const AuthedGroupsRouteRouteChildren: AuthedGroupsRouteRouteChildren = {
  AuthedGroupsSlugRoute: AuthedGroupsSlugRoute,
  AuthedGroupsAllRoute: AuthedGroupsAllRoute,
  AuthedGroupsCreateRoute: AuthedGroupsCreateRoute,
  AuthedGroupsMyRoute: AuthedGroupsMyRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
}

const AuthedGroupsRouteRouteWithChildren =
  AuthedGroupsRouteRoute._addFileChildren(AuthedGroupsRouteRouteChildren)

interface AuthedPostsRouteRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteRouteChildren: AuthedPostsRouteRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteRouteWithChildren =
  AuthedPostsRouteRoute._addFileChildren(AuthedPostsRouteRouteChildren)

interface AuthedProfileRouteRouteChildren {
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedProfileRouteRouteChildren: AuthedProfileRouteRouteChildren = {
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedProfileRouteRouteWithChildren =
  AuthedProfileRouteRoute._addFileChildren(AuthedProfileRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedFeedbacksRouteRoute: typeof AuthedFeedbacksRouteRouteWithChildren
  AuthedGroupsRouteRoute: typeof AuthedGroupsRouteRouteWithChildren
  AuthedPostsRouteRoute: typeof AuthedPostsRouteRouteWithChildren
  AuthedProfileRouteRoute: typeof AuthedProfileRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedFeedbacksRouteRoute: AuthedFeedbacksRouteRouteWithChildren,
  AuthedGroupsRouteRoute: AuthedGroupsRouteRouteWithChildren,
  AuthedPostsRouteRoute: AuthedPostsRouteRouteWithChildren,
  AuthedProfileRouteRoute: AuthedProfileRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
