/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteRouteImport } from './routes/_authed/profile/route'
import { Route as AuthedGroupsRouteRouteImport } from './routes/_authed/groups/route'
import { Route as AuthedFeedbacksRouteRouteImport } from './routes/_authed/feedbacks/route'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedFeedbacksIndexRouteImport } from './routes/_authed/feedbacks/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedGroupsMyRouteImport } from './routes/_authed/groups/my'
import { Route as AuthedGroupsCreateRouteImport } from './routes/_authed/groups/create'
import { Route as AuthedGroupsAllRouteImport } from './routes/_authed/groups/all'
import { Route as AuthedGroupsSlugRouteRouteImport } from './routes/_authed/groups/$slug/route'
import { Route as AuthedAdminGroupsRouteRouteImport } from './routes/_authed/admin/groups/route'
import { Route as AuthedGroupsSlugIndexRouteImport } from './routes/_authed/groups/$slug/index'
import { Route as AuthedAdminGroupsIndexRouteImport } from './routes/_authed/admin/groups/index'
import { Route as AuthedGroupsSlugSettingsRouteImport } from './routes/_authed/groups/$slug/settings'
import { Route as AuthedGroupsSlugMembersRouteImport } from './routes/_authed/groups/$slug/members'
import { Route as AuthedGroupsSlugAdminRouteImport } from './routes/_authed/groups/$slug/admin'
import { Route as AuthedAdminGroupsPendingRouteImport } from './routes/_authed/admin/groups/pending'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRouteRoute = AuthedProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedGroupsRouteRoute = AuthedGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFeedbacksRouteRoute = AuthedFeedbacksRouteRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProfileRouteRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedFeedbacksIndexRoute = AuthedFeedbacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedFeedbacksRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedGroupsMyRoute = AuthedGroupsMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedGroupsCreateRoute = AuthedGroupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedGroupsAllRoute = AuthedGroupsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedGroupsSlugRouteRoute = AuthedGroupsSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthedGroupsRouteRoute,
} as any)
const AuthedAdminGroupsRouteRoute = AuthedAdminGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedGroupsSlugIndexRoute = AuthedGroupsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGroupsSlugRouteRoute,
} as any)
const AuthedAdminGroupsIndexRoute = AuthedAdminGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminGroupsRouteRoute,
} as any)
const AuthedGroupsSlugSettingsRoute =
  AuthedGroupsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedGroupsSlugRouteRoute,
  } as any)
const AuthedGroupsSlugMembersRoute = AuthedGroupsSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedGroupsSlugRouteRoute,
} as any)
const AuthedGroupsSlugAdminRoute = AuthedGroupsSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedGroupsSlugRouteRoute,
} as any)
const AuthedAdminGroupsPendingRoute =
  AuthedAdminGroupsPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthedAdminGroupsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/feedbacks': typeof AuthedFeedbacksRouteRouteWithChildren
  '/groups': typeof AuthedGroupsRouteRouteWithChildren
  '/profile': typeof AuthedProfileRouteRouteWithChildren
  '/admin/groups': typeof AuthedAdminGroupsRouteRouteWithChildren
  '/groups/$slug': typeof AuthedGroupsSlugRouteRouteWithChildren
  '/groups/all': typeof AuthedGroupsAllRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/groups/my': typeof AuthedGroupsMyRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/feedbacks/': typeof AuthedFeedbacksIndexRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/admin/groups/pending': typeof AuthedAdminGroupsPendingRoute
  '/groups/$slug/admin': typeof AuthedGroupsSlugAdminRoute
  '/groups/$slug/members': typeof AuthedGroupsSlugMembersRoute
  '/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/admin/groups/': typeof AuthedAdminGroupsIndexRoute
  '/groups/$slug/': typeof AuthedGroupsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/groups/all': typeof AuthedGroupsAllRoute
  '/groups/create': typeof AuthedGroupsCreateRoute
  '/groups/my': typeof AuthedGroupsMyRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/feedbacks': typeof AuthedFeedbacksIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/admin/groups/pending': typeof AuthedAdminGroupsPendingRoute
  '/groups/$slug/admin': typeof AuthedGroupsSlugAdminRoute
  '/groups/$slug/members': typeof AuthedGroupsSlugMembersRoute
  '/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/admin/groups': typeof AuthedAdminGroupsIndexRoute
  '/groups/$slug': typeof AuthedGroupsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/feedbacks': typeof AuthedFeedbacksRouteRouteWithChildren
  '/_authed/groups': typeof AuthedGroupsRouteRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRouteRouteWithChildren
  '/_authed/admin/groups': typeof AuthedAdminGroupsRouteRouteWithChildren
  '/_authed/groups/$slug': typeof AuthedGroupsSlugRouteRouteWithChildren
  '/_authed/groups/all': typeof AuthedGroupsAllRoute
  '/_authed/groups/create': typeof AuthedGroupsCreateRoute
  '/_authed/groups/my': typeof AuthedGroupsMyRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/feedbacks/': typeof AuthedFeedbacksIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/admin/groups/pending': typeof AuthedAdminGroupsPendingRoute
  '/_authed/groups/$slug/admin': typeof AuthedGroupsSlugAdminRoute
  '/_authed/groups/$slug/members': typeof AuthedGroupsSlugMembersRoute
  '/_authed/groups/$slug/settings': typeof AuthedGroupsSlugSettingsRoute
  '/_authed/admin/groups/': typeof AuthedAdminGroupsIndexRoute
  '/_authed/groups/$slug/': typeof AuthedGroupsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/admin'
    | '/feedbacks'
    | '/groups'
    | '/profile'
    | '/admin/groups'
    | '/groups/$slug'
    | '/groups/all'
    | '/groups/create'
    | '/groups/my'
    | '/admin/'
    | '/feedbacks/'
    | '/groups/'
    | '/profile/'
    | '/admin/groups/pending'
    | '/groups/$slug/admin'
    | '/groups/$slug/members'
    | '/groups/$slug/settings'
    | '/admin/groups/'
    | '/groups/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/groups/all'
    | '/groups/create'
    | '/groups/my'
    | '/admin'
    | '/feedbacks'
    | '/groups'
    | '/profile'
    | '/admin/groups/pending'
    | '/groups/$slug/admin'
    | '/groups/$slug/members'
    | '/groups/$slug/settings'
    | '/admin/groups'
    | '/groups/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/feedbacks'
    | '/_authed/groups'
    | '/_authed/profile'
    | '/_authed/admin/groups'
    | '/_authed/groups/$slug'
    | '/_authed/groups/all'
    | '/_authed/groups/create'
    | '/_authed/groups/my'
    | '/_authed/admin/'
    | '/_authed/feedbacks/'
    | '/_authed/groups/'
    | '/_authed/profile/'
    | '/_authed/admin/groups/pending'
    | '/_authed/groups/$slug/admin'
    | '/_authed/groups/$slug/members'
    | '/_authed/groups/$slug/settings'
    | '/_authed/admin/groups/'
    | '/_authed/groups/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/groups': {
      id: '/_authed/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthedGroupsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/feedbacks': {
      id: '/_authed/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AuthedFeedbacksRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedProfileRouteRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/feedbacks/': {
      id: '/_authed/feedbacks/'
      path: '/'
      fullPath: '/feedbacks/'
      preLoaderRoute: typeof AuthedFeedbacksIndexRouteImport
      parentRoute: typeof AuthedFeedbacksRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/groups/my': {
      id: '/_authed/groups/my'
      path: '/my'
      fullPath: '/groups/my'
      preLoaderRoute: typeof AuthedGroupsMyRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/groups/create': {
      id: '/_authed/groups/create'
      path: '/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AuthedGroupsCreateRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/groups/all': {
      id: '/_authed/groups/all'
      path: '/all'
      fullPath: '/groups/all'
      preLoaderRoute: typeof AuthedGroupsAllRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/groups/$slug': {
      id: '/_authed/groups/$slug'
      path: '/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof AuthedGroupsSlugRouteRouteImport
      parentRoute: typeof AuthedGroupsRouteRoute
    }
    '/_authed/admin/groups': {
      id: '/_authed/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthedAdminGroupsRouteRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/groups/$slug/': {
      id: '/_authed/groups/$slug/'
      path: '/'
      fullPath: '/groups/$slug/'
      preLoaderRoute: typeof AuthedGroupsSlugIndexRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/admin/groups/': {
      id: '/_authed/admin/groups/'
      path: '/'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AuthedAdminGroupsIndexRouteImport
      parentRoute: typeof AuthedAdminGroupsRouteRoute
    }
    '/_authed/groups/$slug/settings': {
      id: '/_authed/groups/$slug/settings'
      path: '/settings'
      fullPath: '/groups/$slug/settings'
      preLoaderRoute: typeof AuthedGroupsSlugSettingsRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/groups/$slug/members': {
      id: '/_authed/groups/$slug/members'
      path: '/members'
      fullPath: '/groups/$slug/members'
      preLoaderRoute: typeof AuthedGroupsSlugMembersRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/groups/$slug/admin': {
      id: '/_authed/groups/$slug/admin'
      path: '/admin'
      fullPath: '/groups/$slug/admin'
      preLoaderRoute: typeof AuthedGroupsSlugAdminRouteImport
      parentRoute: typeof AuthedGroupsSlugRouteRoute
    }
    '/_authed/admin/groups/pending': {
      id: '/_authed/admin/groups/pending'
      path: '/pending'
      fullPath: '/admin/groups/pending'
      preLoaderRoute: typeof AuthedAdminGroupsPendingRouteImport
      parentRoute: typeof AuthedAdminGroupsRouteRoute
    }
  }
}

interface AuthedAdminGroupsRouteRouteChildren {
  AuthedAdminGroupsPendingRoute: typeof AuthedAdminGroupsPendingRoute
  AuthedAdminGroupsIndexRoute: typeof AuthedAdminGroupsIndexRoute
}

const AuthedAdminGroupsRouteRouteChildren: AuthedAdminGroupsRouteRouteChildren =
  {
    AuthedAdminGroupsPendingRoute: AuthedAdminGroupsPendingRoute,
    AuthedAdminGroupsIndexRoute: AuthedAdminGroupsIndexRoute,
  }

const AuthedAdminGroupsRouteRouteWithChildren =
  AuthedAdminGroupsRouteRoute._addFileChildren(
    AuthedAdminGroupsRouteRouteChildren,
  )

interface AuthedAdminRouteRouteChildren {
  AuthedAdminGroupsRouteRoute: typeof AuthedAdminGroupsRouteRouteWithChildren
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminGroupsRouteRoute: AuthedAdminGroupsRouteRouteWithChildren,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedFeedbacksRouteRouteChildren {
  AuthedFeedbacksIndexRoute: typeof AuthedFeedbacksIndexRoute
}

const AuthedFeedbacksRouteRouteChildren: AuthedFeedbacksRouteRouteChildren = {
  AuthedFeedbacksIndexRoute: AuthedFeedbacksIndexRoute,
}

const AuthedFeedbacksRouteRouteWithChildren =
  AuthedFeedbacksRouteRoute._addFileChildren(AuthedFeedbacksRouteRouteChildren)

interface AuthedGroupsSlugRouteRouteChildren {
  AuthedGroupsSlugAdminRoute: typeof AuthedGroupsSlugAdminRoute
  AuthedGroupsSlugMembersRoute: typeof AuthedGroupsSlugMembersRoute
  AuthedGroupsSlugSettingsRoute: typeof AuthedGroupsSlugSettingsRoute
  AuthedGroupsSlugIndexRoute: typeof AuthedGroupsSlugIndexRoute
}

const AuthedGroupsSlugRouteRouteChildren: AuthedGroupsSlugRouteRouteChildren = {
  AuthedGroupsSlugAdminRoute: AuthedGroupsSlugAdminRoute,
  AuthedGroupsSlugMembersRoute: AuthedGroupsSlugMembersRoute,
  AuthedGroupsSlugSettingsRoute: AuthedGroupsSlugSettingsRoute,
  AuthedGroupsSlugIndexRoute: AuthedGroupsSlugIndexRoute,
}

const AuthedGroupsSlugRouteRouteWithChildren =
  AuthedGroupsSlugRouteRoute._addFileChildren(
    AuthedGroupsSlugRouteRouteChildren,
  )

interface AuthedGroupsRouteRouteChildren {
  AuthedGroupsSlugRouteRoute: typeof AuthedGroupsSlugRouteRouteWithChildren
  AuthedGroupsAllRoute: typeof AuthedGroupsAllRoute
  AuthedGroupsCreateRoute: typeof AuthedGroupsCreateRoute
  AuthedGroupsMyRoute: typeof AuthedGroupsMyRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
}

const AuthedGroupsRouteRouteChildren: AuthedGroupsRouteRouteChildren = {
  AuthedGroupsSlugRouteRoute: AuthedGroupsSlugRouteRouteWithChildren,
  AuthedGroupsAllRoute: AuthedGroupsAllRoute,
  AuthedGroupsCreateRoute: AuthedGroupsCreateRoute,
  AuthedGroupsMyRoute: AuthedGroupsMyRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
}

const AuthedGroupsRouteRouteWithChildren =
  AuthedGroupsRouteRoute._addFileChildren(AuthedGroupsRouteRouteChildren)

interface AuthedProfileRouteRouteChildren {
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedProfileRouteRouteChildren: AuthedProfileRouteRouteChildren = {
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedProfileRouteRouteWithChildren =
  AuthedProfileRouteRoute._addFileChildren(AuthedProfileRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedFeedbacksRouteRoute: typeof AuthedFeedbacksRouteRouteWithChildren
  AuthedGroupsRouteRoute: typeof AuthedGroupsRouteRouteWithChildren
  AuthedProfileRouteRoute: typeof AuthedProfileRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedFeedbacksRouteRoute: AuthedFeedbacksRouteRouteWithChildren,
  AuthedGroupsRouteRoute: AuthedGroupsRouteRouteWithChildren,
  AuthedProfileRouteRoute: AuthedProfileRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
